AWSTemplateFormatVersion: "2010-09-09"
Description: "This Cloudformation Stack creates an EC2 instance and Security Group"
Parameters:
  WordpressInstanceKeyName:
    Type: String
    Default: "MyMacKey"
  WordpressInstanceAmi:
    Type: String
    Default: "ami-0ca285d4c2cda3300"

Resources:
  WordpressEC2Instance: #Logical Name or Logical ID, Name or ID has to be unique within a template
    Type: AWS::EC2::Instance
    Properties:
      KeyName: !Ref WordpressInstanceKeyName
      ImageId: !Ref WordpressInstanceAmi
      InstanceType: "t2.micro"
      SecurityGroupIds:
        - !Ref WordpressSecurityGroup

  WordpressSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      GroupDescription: "This security group is used for Wordpress EC2 Instance"
      GroupName: "WordpressSecurityGroup"
      SecurityGroupEgress: 
        - IpProtocol: -1
          FromPort: -1
          ToPort: -1
          CidrIp: 0.0.0.0/0
      SecurityGroupIngress: 
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      VpcId: "vpc-0edf3a49f18791301"